# Generated by Django 5.1.2 on 2024-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_project_remove_command_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(0, 'Нужно сделать'), (1, 'В работе'), (2, 'Сделано'), (3, 'Доработать'), (4, 'Другое')], default='Нужно сделать', max_length=20),
        ),
    ]
