# Generated by Django 5.1.2 on 2024-12-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_start',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[], default='Низкий', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Нужно сделать', 'Нужно сделать'), ('В работе', 'В работе'), ('Сделано', 'Сделано'), ('Доработать', 'Доработать'), ('Другое', 'Другое')], default='Нужно сделать', max_length=20),
        ),
    ]
