# Generated by Django 5.1.2 on 2024-12-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.command'),
        ),
    ]
